In [3]:
import numpy as np
from scipy.spatial import Delaunay


from sampling import SobolSampler

In [6]:
N = 3

num_sobol_samples = 4
sobol_sampler = SobolSampler(bounds=[(0, 0.5), (-0.5, 0.5), (0.01, 1)])
samples = sobol_sampler.samples(num_samples_po2=num_sobol_samples)
print("samples", samples)


samples [[ 0.30727574  0.18874299  0.61318546]
 [ 0.20499728 -0.13949156  0.27204225]
 [ 0.11010225  0.38383539  0.76818743]
 [ 0.40229069 -0.44396658  0.11908917]]


In [7]:
# Compute the 3D triangulation
tri = Delaunay(samples)

# Inspect the simplices
print(tri.simplices.shape)

(1, 4)


In [8]:
edges = set()

for simplex in tri.simplices:
    for i in range(N+1):
        for j in range(i + 1, N+1):            
            edge = tuple(sorted((simplex[i], simplex[j])))
            edges.add(edge)


unique_edges = list(edges)
unique_edges

[(0, 1), (1, 2), (0, 3), (2, 3), (0, 2), (1, 3)]